"""
Seeded logistics data for the Simulated ERP.

Geography: San Francisco Bay Area.
All coordinates are real Bay Area locations.
Stock levels, driver positions, and zone metrics are plausible
but synthesised for demonstration purposes.
"""
from datetime import datetime, timezone

_NOW = datetime.now(timezone.utc).isoformat()

# ── Warehouses ─────────────────────────────────────────────────────────────────

WAREHOUSES: list[dict] = [
    {
        "id": "WH-SF01",
        "name": "SF Mission District Fulfillment Center",
        "address": "2300 Harrison St, San Francisco CA 94110",
        "lat": 37.7599,
        "lon": -122.4148,
        "zones_served": ["central_sf", "soma_mission", "peninsula"],
        "stock": {"general": 820, "fragile": 295, "refrigerated": 140, "hazardous": 38},
        "capacity_units": 1200,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-OAK01",
        "name": "Oakland Harbor Distribution Hub",
        "address": "7th St Terminal, Oakland CA 94607",
        "lat": 37.8044,
        "lon": -122.2712,
        "zones_served": ["east_bay", "outer_east", "north_bay"],
        "stock": {"general": 640, "fragile": 178, "refrigerated": 98, "hazardous": 22},
        "capacity_units": 1000,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-SJ01",
        "name": "San Jose Tech Corridor Depot",
        "address": "1800 Bering Dr, San Jose CA 95112",
        "lat": 37.3382,
        "lon": -121.8863,
        "zones_served": ["south_bay", "outer_east", "outer_south"],
        "stock": {"general": 530, "fragile": 210, "refrigerated": 72, "hazardous": 18},
        "capacity_units": 900,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-SSF01",
        "name": "South San Francisco Peninsula Hub",
        "address": "400 Oyster Point Blvd, South San Francisco CA 94080",
        "lat": 37.6527,
        "lon": -122.4477,
        "zones_served": ["peninsula", "central_sf", "soma_mission"],
        "stock": {"general": 710, "fragile": 162, "refrigerated": 205, "hazardous": 31},
        "capacity_units": 1100,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-MRN01",
        "name": "Marin County Logistics Center",
        "address": "100 Rowland Way, Novato CA 94945",
        "lat": 37.9735,
        "lon": -122.5311,
        "zones_served": ["north_bay", "central_sf", "outer_west"],
        "stock": {"general": 380, "fragile": 95, "refrigerated": 48, "hazardous": 11},
        "capacity_units": 600,
        "active": True,
        "last_restocked": _NOW,
    },
]


# ── Drivers ────────────────────────────────────────────────────────────────────

DRIVERS: list[dict] = [
    {
        "id": "DRV-001",
        "name": "Marcus Johnson",
        "vehicle_type": "van",
        "lat": 37.7920,
        "lon": -122.3985,
        "available": True,
        "current_load_kg": 75.0,
        "max_load_kg": 500.0,
        "active_deliveries": 2,
        "rating": 4.8,
        "zone_familiarity": ["central_sf", "soma_mission", "east_bay"],
        "shift_end_utc": "2026-05-05T20:00:00Z",
    },
    {
        "id": "DRV-002",
        "name": "Aisha Patel",
        "vehicle_type": "van",
        "lat": 37.7588,
        "lon": -122.4148,
        "available": True,
        "current_load_kg": 0.0,
        "max_load_kg": 500.0,
        "active_deliveries": 0,
        "rating": 4.9,
        "zone_familiarity": ["central_sf", "soma_mission", "peninsula"],
        "shift_end_utc": "2026-05-05T22:00:00Z",
    },
    {
        "id": "DRV-003",
        "name": "Carlos Rodriguez",
        "vehicle_type": "truck",
        "lat": 37.3395,
        "lon": -121.8910,
        "available": True,
        "current_load_kg": 180.0,
        "max_load_kg": 2000.0,
        "active_deliveries": 3,
        "rating": 4.6,
        "zone_familiarity": ["south_bay", "outer_east", "outer_south"],
        "shift_end_utc": "2026-05-05T19:00:00Z",
    },
    {
        "id": "DRV-004",
        "name": "Mei Chen",
        "vehicle_type": "motorbike",
        "lat": 37.7855,
        "lon": -122.4000,
        "available": True,
        "current_load_kg": 8.0,
        "max_load_kg": 50.0,
        "active_deliveries": 1,
        "rating": 4.7,
        "zone_familiarity": ["central_sf", "soma_mission"],
        "shift_end_utc": "2026-05-05T18:30:00Z",
    },
    {
        "id": "DRV-005",
        "name": "Jordan Williams",
        "vehicle_type": "van",
        "lat": 37.9740,
        "lon": -122.5315,
        "available": True,
        "current_load_kg": 0.0,
        "max_load_kg": 800.0,
        "active_deliveries": 0,
        "rating": 4.5,
        "zone_familiarity": ["north_bay", "central_sf"],
        "shift_end_utc": "2026-05-05T21:00:00Z",
    },
    {
        "id": "DRV-006",
        "name": "Priya Sharma",
        "vehicle_type": "truck",
        "lat": 37.8040,
        "lon": -122.2720,
        "available": False,   # currently on a delivery
        "current_load_kg": 320.0,
        "max_load_kg": 2000.0,
        "active_deliveries": 4,
        "rating": 4.8,
        "zone_familiarity": ["east_bay", "outer_east", "south_bay"],
        "shift_end_utc": "2026-05-05T20:30:00Z",
    },
    {
        "id": "DRV-007",
        "name": "Diego Morales",
        "vehicle_type": "van",
        "lat": 37.6688,
        "lon": -122.0808,
        "available": True,
        "current_load_kg": 140.0,
        "max_load_kg": 500.0,
        "active_deliveries": 2,
        "rating": 4.4,
        "zone_familiarity": ["south_bay", "outer_east"],
        "shift_end_utc": "2026-05-05T19:30:00Z",
    },
    {
        "id": "DRV-008",
        "name": "Yuki Tanaka",
        "vehicle_type": "motorbike",
        "lat": 37.8030,
        "lon": -122.2410,
        "available": True,
        "current_load_kg": 5.0,
        "max_load_kg": 50.0,
        "active_deliveries": 1,
        "rating": 4.7,
        "zone_familiarity": ["central_sf", "east_bay"],
        "shift_end_utc": "2026-05-05T17:00:00Z",
    },
    {
        "id": "DRV-009",
        "name": "Amara Okonkwo",
        "vehicle_type": "van",
        "lat": 37.8305,
        "lon": -122.2441,
        "available": True,
        "current_load_kg": 290.0,
        "max_load_kg": 600.0,
        "active_deliveries": 4,
        "rating": 4.3,
        "zone_familiarity": ["east_bay", "north_bay", "outer_east"],
        "shift_end_utc": "2026-05-05T18:00:00Z",
    },
    {
        "id": "DRV-010",
        "name": "Tyler Nguyen",
        "vehicle_type": "truck",
        "lat": 37.6527,
        "lon": -122.4477,
        "available": False,   # currently on a delivery
        "current_load_kg": 460.0,
        "max_load_kg": 2000.0,
        "active_deliveries": 5,
        "rating": 4.6,
        "zone_familiarity": ["peninsula", "central_sf", "soma_mission"],
        "shift_end_utc": "2026-05-05T20:00:00Z",
    },
    {
        "id": "DRV-011",
        "name": "Sofia Espinoza",
        "vehicle_type": "van",
        "lat": 37.7599,
        "lon": -122.4150,
        "available": False,   # currently on a delivery
        "current_load_kg": 260.0,
        "max_load_kg": 500.0,
        "active_deliveries": 3,
        "rating": 4.5,
        "zone_familiarity": ["soma_mission", "south_bay"],
        "shift_end_utc": "2026-05-05T21:30:00Z",
    },
    {
        "id": "DRV-012",
        "name": "Reza Ahmadi",
        "vehicle_type": "motorbike",
        "lat": 37.7880,
        "lon": -122.4074,
        "available": True,
        "current_load_kg": 6.0,
        "max_load_kg": 50.0,
        "active_deliveries": 1,
        "rating": 4.9,
        "zone_familiarity": ["central_sf", "soma_mission"],
        "shift_end_utc": "2026-05-05T23:00:00Z",
    },
]


# ── Delivery zones ─────────────────────────────────────────────────────────────

ZONES: dict[str, dict] = {
    "central_sf": {
        "id": "central_sf",
        "name": "SF Financial District / Union Square",
        "example_neighborhoods": ["Financial District", "Union Square", "Chinatown", "Tenderloin"],
        "centroid": {"lat": 37.795, "lon": -122.404},
        "delivery_success_rate": 0.96,
        "avg_transit_hours": 1.2,
        "demand_pressure": 0.91,
        "active_routes": 38,
        "complaint_rate": 0.03,
        "last_30_days": {
            "total_deliveries": 2104,
            "successful": 2020,
            "failed": 84,
            "avg_delay_minutes": 7,
        },
    },
    "soma_mission": {
        "id": "soma_mission",
        "name": "SoMa / Mission / Castro",
        "example_neighborhoods": ["SoMa", "Mission District", "Castro", "Noe Valley"],
        "centroid": {"lat": 37.768, "lon": -122.414},
        "delivery_success_rate": 0.94,
        "avg_transit_hours": 1.5,
        "demand_pressure": 0.82,
        "active_routes": 28,
        "complaint_rate": 0.04,
        "last_30_days": {
            "total_deliveries": 1520,
            "successful": 1429,
            "failed": 91,
            "avg_delay_minutes": 12,
        },
    },
    "east_bay": {
        "id": "east_bay",
        "name": "East Bay (Oakland / Berkeley)",
        "example_neighborhoods": ["Downtown Oakland", "Temescal", "Rockridge", "Berkeley Hills"],
        "centroid": {"lat": 37.834, "lon": -122.245},
        "delivery_success_rate": 0.91,
        "avg_transit_hours": 1.7,
        "demand_pressure": 0.75,
        "active_routes": 24,
        "complaint_rate": 0.07,
        "last_30_days": {
            "total_deliveries": 1380,
            "successful": 1256,
            "failed": 124,
            "avg_delay_minutes": 16,
        },
    },
    "south_bay": {
        "id": "south_bay",
        "name": "South Bay (San Jose / Santa Clara)",
        "example_neighborhoods": ["Downtown SJ", "Willow Glen", "Santa Clara", "Sunnyvale"],
        "centroid": {"lat": 37.360, "lon": -121.928},
        "delivery_success_rate": 0.93,
        "avg_transit_hours": 1.6,
        "demand_pressure": 0.68,
        "active_routes": 21,
        "complaint_rate": 0.05,
        "last_30_days": {
            "total_deliveries": 1190,
            "successful": 1107,
            "failed": 83,
            "avg_delay_minutes": 13,
        },
    },
    "peninsula": {
        "id": "peninsula",
        "name": "Peninsula (Daly City / San Mateo)",
        "example_neighborhoods": ["Daly City", "South San Francisco", "San Mateo", "Redwood City"],
        "centroid": {"lat": 37.594, "lon": -122.435},
        "delivery_success_rate": 0.92,
        "avg_transit_hours": 1.8,
        "demand_pressure": 0.71,
        "active_routes": 20,
        "complaint_rate": 0.06,
        "last_30_days": {
            "total_deliveries": 1040,
            "successful": 957,
            "failed": 83,
            "avg_delay_minutes": 15,
        },
    },
    "north_bay": {
        "id": "north_bay",
        "name": "North Bay (Marin / Novato)",
        "example_neighborhoods": ["San Rafael", "Novato", "Mill Valley", "Fairfax"],
        "centroid": {"lat": 38.005, "lon": -122.510},
        "delivery_success_rate": 0.90,
        "avg_transit_hours": 2.2,
        "demand_pressure": 0.55,
        "active_routes": 14,
        "complaint_rate": 0.08,
        "last_30_days": {
            "total_deliveries": 720,
            "successful": 648,
            "failed": 72,
            "avg_delay_minutes": 22,
        },
    },
    "outer_east": {
        "id": "outer_east",
        "name": "Outer East (Hayward / Fremont)",
        "example_neighborhoods": ["Hayward", "Fremont", "Newark", "Union City"],
        "centroid": {"lat": 37.640, "lon": -122.045},
        "delivery_success_rate": 0.83,
        "avg_transit_hours": 2.8,
        "demand_pressure": 0.44,
        "active_routes": 11,
        "complaint_rate": 0.14,
        "last_30_days": {
            "total_deliveries": 590,
            "successful": 490,
            "failed": 100,
            "avg_delay_minutes": 34,
        },
    },
    "outer_south": {
        "id": "outer_south",
        "name": "Outer South (Gilroy / Morgan Hill)",
        "example_neighborhoods": ["Gilroy", "Morgan Hill", "Los Gatos", "Campbell"],
        "centroid": {"lat": 37.100, "lon": -121.800},
        "delivery_success_rate": 0.87,
        "avg_transit_hours": 2.5,
        "demand_pressure": 0.48,
        "active_routes": 13,
        "complaint_rate": 0.11,
        "last_30_days": {
            "total_deliveries": 740,
            "successful": 644,
            "failed": 96,
            "avg_delay_minutes": 28,
        },
    },
    "outer_west": {
        "id": "outer_west",
        "name": "Outer West (Pacifica / Half Moon Bay)",
        "example_neighborhoods": ["Pacifica", "Half Moon Bay", "Montara", "El Granada"],
        "centroid": {"lat": 37.560, "lon": -122.555},
        "delivery_success_rate": 0.88,
        "avg_transit_hours": 2.4,
        "demand_pressure": 0.38,
        "active_routes": 8,
        "complaint_rate": 0.10,
        "last_30_days": {
            "total_deliveries": 410,
            "successful": 361,
            "failed": 49,
            "avg_delay_minutes": 26,
        },
    },
}


# ── Pending order queue ────────────────────────────────────────────────────────

PENDING_ORDERS: list[dict] = [
    {
        "order_id": "ORD-2026-0501",
        "customer": "UCSF Medical Center",
        "destination_lat": 37.7631,
        "destination_lon": -122.4576,
        "destination_label": "505 Parnassus Ave, San Francisco CA 94143",
        "order_value": 7200.00,
        "weight_kg": 38.0,
        "cargo_type": "fragile",
        "time_window_hours": 2.5,
        "priority": "critical",
        "created_at": "2026-05-05T07:30:00Z",
    },
    {
        "order_id": "ORD-2026-0502",
        "customer": "Salesforce Tower Office",
        "destination_lat": 37.7897,
        "destination_lon": -122.3972,
        "destination_label": "415 Mission St, San Francisco CA 94105",
        "order_value": 2600.00,
        "weight_kg": 24.0,
        "cargo_type": "fragile",
        "time_window_hours": 4.0,
        "priority": "standard",
        "created_at": "2026-05-05T07:45:00Z",
    },
    {
        "order_id": "ORD-2026-0503",
        "customer": "Mission Community Market",
        "destination_lat": 37.7599,
        "destination_lon": -122.4148,
        "destination_label": "3025 24th St, San Francisco CA 94110",
        "order_value": 940.00,
        "weight_kg": 110.0,
        "cargo_type": "refrigerated",
        "time_window_hours": 3.0,
        "priority": "urgent",
        "created_at": "2026-05-05T08:00:00Z",
    },
    {
        "order_id": "ORD-2026-0504",
        "customer": "Stanford Shopping Center",
        "destination_lat": 37.4419,
        "destination_lon": -122.1430,
        "destination_label": "180 El Camino Real, Palo Alto CA 94304",
        "order_value": 3400.00,
        "weight_kg": 60.0,
        "cargo_type": "general",
        "time_window_hours": 6.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:10:00Z",
    },
    {
        "order_id": "ORD-2026-0505",
        "customer": "Kaiser Permanente Oakland",
        "destination_lat": 37.8044,
        "destination_lon": -122.2635,
        "destination_label": "3600 Broadway, Oakland CA 94611",
        "order_value": 5300.00,
        "weight_kg": 16.0,
        "cargo_type": "fragile",
        "time_window_hours": 3.5,
        "priority": "urgent",
        "created_at": "2026-05-05T08:15:00Z",
    },
    {
        "order_id": "ORD-2026-0506",
        "customer": "Salesforce East Bay Hub",
        "destination_lat": 37.8100,
        "destination_lon": -122.2680,
        "destination_label": "300 Lakeside Dr, Oakland CA 94612",
        "order_value": 1800.00,
        "weight_kg": 88.0,
        "cargo_type": "general",
        "time_window_hours": 5.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:20:00Z",
    },
    {
        "order_id": "ORD-2026-0507",
        "customer": "Fremont Auto Parts",
        "destination_lat": 37.5485,
        "destination_lon": -121.9886,
        "destination_label": "3500 Mowry Ave, Fremont CA 94538",
        "order_value": 4500.00,
        "weight_kg": 295.0,
        "cargo_type": "general",
        "time_window_hours": 8.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:25:00Z",
    },
    {
        "order_id": "ORD-2026-0508",
        "customer": "San Jose Museum of Art",
        "destination_lat": 37.3368,
        "destination_lon": -121.8900,
        "destination_label": "110 S Market St, San Jose CA 95113",
        "order_value": 16000.00,
        "weight_kg": 11.0,
        "cargo_type": "fragile",
        "time_window_hours": 2.0,
        "priority": "critical",
        "created_at": "2026-05-05T08:30:00Z",
    },
    {
        "order_id": "ORD-2026-0509",
        "customer": "Marin Organics Co-op",
        "destination_lat": 37.9735,
        "destination_lon": -122.5311,
        "destination_label": "880 Grant Ave, Novato CA 94945",
        "order_value": 1200.00,
        "weight_kg": 82.0,
        "cargo_type": "refrigerated",
        "time_window_hours": 4.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:35:00Z",
    },
    {
        "order_id": "ORD-2026-0510",
        "customer": "Hayward Construction Supply",
        "destination_lat": 37.6688,
        "destination_lon": -122.0808,
        "destination_label": "24301 Clawiter Rd, Hayward CA 94545",
        "order_value": 2800.00,
        "weight_kg": 460.0,
        "cargo_type": "general",
        "time_window_hours": 10.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:40:00Z",
    },
]
