"""
Seeded logistics data for the Simulated ERP.

Geography: Greater London and its immediate borders.
All coordinates are real London locations.
Stock levels, driver positions, and zone metrics are plausible
but synthesised for demonstration purposes.
"""
from datetime import datetime, timezone

_NOW = datetime.now(timezone.utc).isoformat()

# ── Warehouses ─────────────────────────────────────────────────────────────────

WAREHOUSES: list[dict] = [
    {
        "id": "WH-E01",
        "name": "Stratford Logistics Hub",
        "address": "Stratford High Street, London E15 2NE",
        "lat": 51.5416,
        "lon": -0.0001,
        "zones_served": ["east", "central", "outer_east", "north"],
        "stock": {"general": 847, "fragile": 312, "refrigerated": 138, "hazardous": 45},
        "capacity_units": 1200,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-NW01",
        "name": "Wembley Distribution Centre",
        "address": "Engineers Way, Wembley HA9 0FJ",
        "lat": 51.5561,
        "lon": -0.2796,
        "zones_served": ["north", "west", "outer_north", "outer_west", "central"],
        "stock": {"general": 623, "fragile": 189, "refrigerated": 94, "hazardous": 28},
        "capacity_units": 1000,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-S01",
        "name": "Croydon Fulfilment Centre",
        "address": "Purley Way, Croydon CR0 4RQ",
        "lat": 51.3727,
        "lon": -0.1099,
        "zones_served": ["south", "outer_south", "central"],
        "stock": {"general": 511, "fragile": 203, "refrigerated": 67, "hazardous": 19},
        "capacity_units": 800,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-W01",
        "name": "Park Royal Depot",
        "address": "Chase Road, Park Royal NW10 6HZ",
        "lat": 51.5302,
        "lon": -0.2805,
        "zones_served": ["west", "central", "outer_west", "north"],
        "stock": {"general": 734, "fragile": 156, "refrigerated": 212, "hazardous": 33},
        "capacity_units": 1100,
        "active": True,
        "last_restocked": _NOW,
    },
    {
        "id": "WH-SE01",
        "name": "Greenwich Warehouse",
        "address": "Blackwall Lane, Greenwich SE10 0AR",
        "lat": 51.4826,
        "lon":  0.0077,
        "zones_served": ["east", "south", "outer_east", "central"],
        "stock": {"general": 389, "fragile": 97, "refrigerated": 51, "hazardous": 12},
        "capacity_units": 600,
        "active": True,
        "last_restocked": _NOW,
    },
]


# ── Drivers ────────────────────────────────────────────────────────────────────

DRIVERS: list[dict] = [
    {
        "id": "DRV-001",
        "name": "Marcus Webb",
        "vehicle_type": "van",
        "vehicle_reg": "LK21 AXB",
        "lat": 51.5235,
        "lon": -0.0755,
        "available": True,
        "current_load_kg": 85.0,
        "max_load_kg": 500.0,
        "active_deliveries": 2,
        "rating": 4.8,
        "zone_familiarity": ["central", "east", "north"],
        "shift_end_utc": "2026-05-05T18:00:00Z",
    },
    {
        "id": "DRV-002",
        "name": "Sarah Chen",
        "vehicle_type": "van",
        "vehicle_reg": "LN70 BPR",
        "lat": 51.5309,
        "lon": -0.1237,
        "available": True,
        "current_load_kg": 0.0,
        "max_load_kg": 500.0,
        "active_deliveries": 0,
        "rating": 4.9,
        "zone_familiarity": ["central", "north", "west"],
        "shift_end_utc": "2026-05-05T20:00:00Z",
    },
    {
        "id": "DRV-003",
        "name": "Jamal Osei",
        "vehicle_type": "van",
        "vehicle_reg": "SG19 MNF",
        "lat": 51.4616,
        "lon": -0.1145,
        "available": True,
        "current_load_kg": 210.0,
        "max_load_kg": 500.0,
        "active_deliveries": 3,
        "rating": 4.6,
        "zone_familiarity": ["south", "central", "outer_south"],
        "shift_end_utc": "2026-05-05T17:00:00Z",
    },
    {
        "id": "DRV-004",
        "name": "Priya Sharma",
        "vehicle_type": "motorbike",
        "vehicle_reg": "KX22 DLT",
        "lat": 51.5054,
        "lon": -0.0235,
        "available": True,
        "current_load_kg": 12.0,
        "max_load_kg": 50.0,
        "active_deliveries": 1,
        "rating": 4.7,
        "zone_familiarity": ["east", "central"],
        "shift_end_utc": "2026-05-05T16:30:00Z",
    },
    {
        "id": "DRV-005",
        "name": "Tommy Fraser",
        "vehicle_type": "van",
        "vehicle_reg": "LD20 VWT",
        "lat": 51.4927,
        "lon": -0.2235,
        "available": True,
        "current_load_kg": 0.0,
        "max_load_kg": 800.0,
        "active_deliveries": 0,
        "rating": 4.5,
        "zone_familiarity": ["west", "central", "outer_west"],
        "shift_end_utc": "2026-05-05T19:00:00Z",
    },
    {
        "id": "DRV-006",
        "name": "Anya Kowalski",
        "vehicle_type": "van",
        "vehicle_reg": "YR68 CPJ",
        "lat": 51.5454,
        "lon": -0.0577,
        "available": False,   # currently on a delivery
        "current_load_kg": 340.0,
        "max_load_kg": 500.0,
        "active_deliveries": 4,
        "rating": 4.8,
        "zone_familiarity": ["east", "north", "central"],
        "shift_end_utc": "2026-05-05T18:30:00Z",
    },
    {
        "id": "DRV-007",
        "name": "Dan Okafor",
        "vehicle_type": "van",
        "vehicle_reg": "FP17 HKW",
        "lat": 51.4614,
        "lon": -0.0210,
        "available": True,
        "current_load_kg": 155.0,
        "max_load_kg": 500.0,
        "active_deliveries": 2,
        "rating": 4.4,
        "zone_familiarity": ["south", "east", "outer_east"],
        "shift_end_utc": "2026-05-05T17:30:00Z",
    },
    {
        "id": "DRV-008",
        "name": "Grace Kim",
        "vehicle_type": "van",
        "vehicle_reg": "WU71 QAS",
        "lat": 51.5113,
        "lon": -0.3018,
        "available": True,
        "current_load_kg": 45.0,
        "max_load_kg": 500.0,
        "active_deliveries": 1,
        "rating": 4.7,
        "zone_familiarity": ["west", "outer_west", "north"],
        "shift_end_utc": "2026-05-05T20:00:00Z",
    },
    {
        "id": "DRV-009",
        "name": "Raj Patel",
        "vehicle_type": "van",
        "vehicle_reg": "GE19 RXN",
        "lat": 51.5362,
        "lon":  0.0798,
        "available": True,
        "current_load_kg": 320.0,
        "max_load_kg": 600.0,
        "active_deliveries": 4,
        "rating": 4.3,
        "zone_familiarity": ["east", "outer_east", "north"],
        "shift_end_utc": "2026-05-05T16:00:00Z",
    },
    {
        "id": "DRV-010",
        "name": "Emma Walsh",
        "vehicle_type": "van",
        "vehicle_reg": "BT20 LMJ",
        "lat": 51.3789,
        "lon": -0.1105,
        "available": False,   # currently on a delivery
        "current_load_kg": 480.0,
        "max_load_kg": 500.0,
        "active_deliveries": 5,
        "rating": 4.6,
        "zone_familiarity": ["outer_south", "south"],
        "shift_end_utc": "2026-05-05T18:00:00Z",
    },
    {
        "id": "DRV-011",
        "name": "Leon Baptiste",
        "vehicle_type": "van",
        "vehicle_reg": "NK21 VHD",
        "lat": 51.5884,
        "lon": -0.0710,
        "available": False,   # currently on a delivery
        "current_load_kg": 280.0,
        "max_load_kg": 500.0,
        "active_deliveries": 3,
        "rating": 4.5,
        "zone_familiarity": ["north", "outer_north", "east"],
        "shift_end_utc": "2026-05-05T19:30:00Z",
    },
    {
        "id": "DRV-012",
        "name": "Mia Torres",
        "vehicle_type": "motorbike",
        "vehicle_reg": "PL22 GKW",
        "lat": 51.4796,
        "lon": -0.1943,
        "available": True,
        "current_load_kg": 8.0,
        "max_load_kg": 50.0,
        "active_deliveries": 1,
        "rating": 4.9,
        "zone_familiarity": ["west", "central", "south"],
        "shift_end_utc": "2026-05-05T21:00:00Z",
    },
]


# ── Delivery zones ─────────────────────────────────────────────────────────────

ZONES: dict[str, dict] = {
    "central": {
        "id": "central",
        "name": "Central London",
        "example_postcodes": ["EC1", "EC2", "WC1", "WC2", "W1", "SW1", "SE1"],
        "centroid": {"lat": 51.511, "lon": -0.118},
        "delivery_success_rate": 0.96,
        "avg_transit_hours": 1.4,
        "demand_pressure": 0.89,
        "active_routes": 34,
        "complaint_rate": 0.03,
        "last_30_days": {
            "total_deliveries": 1842,
            "successful": 1768,
            "failed": 74,
            "avg_delay_minutes": 8,
        },
    },
    "north": {
        "id": "north",
        "name": "North London",
        "example_postcodes": ["N1", "N4", "N5", "N7", "N8", "N10", "N15", "N16", "N22"],
        "centroid": {"lat": 51.576, "lon": -0.085},
        "delivery_success_rate": 0.93,
        "avg_transit_hours": 1.8,
        "demand_pressure": 0.71,
        "active_routes": 22,
        "complaint_rate": 0.05,
        "last_30_days": {
            "total_deliveries": 1203,
            "successful": 1119,
            "failed": 84,
            "avg_delay_minutes": 14,
        },
    },
    "east": {
        "id": "east",
        "name": "East London",
        "example_postcodes": ["E1", "E2", "E3", "E8", "E9", "E14", "E15", "E16", "E20"],
        "centroid": {"lat": 51.515, "lon": 0.020},
        "delivery_success_rate": 0.91,
        "avg_transit_hours": 1.6,
        "demand_pressure": 0.78,
        "active_routes": 27,
        "complaint_rate": 0.07,
        "last_30_days": {
            "total_deliveries": 1567,
            "successful": 1426,
            "failed": 141,
            "avg_delay_minutes": 18,
        },
    },
    "south": {
        "id": "south",
        "name": "South London",
        "example_postcodes": ["SE5", "SE15", "SE17", "SE24", "SW4", "SW9", "SW16"],
        "centroid": {"lat": 51.461, "lon": -0.085},
        "delivery_success_rate": 0.89,
        "avg_transit_hours": 2.1,
        "demand_pressure": 0.62,
        "active_routes": 19,
        "complaint_rate": 0.09,
        "last_30_days": {
            "total_deliveries": 987,
            "successful": 878,
            "failed": 109,
            "avg_delay_minutes": 22,
        },
    },
    "west": {
        "id": "west",
        "name": "West London",
        "example_postcodes": ["W3", "W4", "W5", "W6", "W7", "W12", "W13", "W14"],
        "centroid": {"lat": 51.505, "lon": -0.280},
        "delivery_success_rate": 0.94,
        "avg_transit_hours": 1.7,
        "demand_pressure": 0.74,
        "active_routes": 23,
        "complaint_rate": 0.04,
        "last_30_days": {
            "total_deliveries": 1124,
            "successful": 1057,
            "failed": 67,
            "avg_delay_minutes": 11,
        },
    },
    "outer_east": {
        "id": "outer_east",
        "name": "Outer East (Essex borders)",
        "example_postcodes": ["RM1", "RM8", "RM12", "DA1", "DA6", "IG1", "IG11"],
        "centroid": {"lat": 51.510, "lon": 0.240},
        "delivery_success_rate": 0.83,
        "avg_transit_hours": 2.8,
        "demand_pressure": 0.44,
        "active_routes": 11,
        "complaint_rate": 0.14,
        "last_30_days": {
            "total_deliveries": 612,
            "successful": 508,
            "failed": 104,
            "avg_delay_minutes": 34,
        },
    },
    "outer_south": {
        "id": "outer_south",
        "name": "Outer South (Surrey borders)",
        "example_postcodes": ["CR0", "CR4", "BR1", "BR3", "SM1", "SM4", "KT1"],
        "centroid": {"lat": 51.365, "lon": -0.080},
        "delivery_success_rate": 0.87,
        "avg_transit_hours": 2.4,
        "demand_pressure": 0.51,
        "active_routes": 14,
        "complaint_rate": 0.11,
        "last_30_days": {
            "total_deliveries": 789,
            "successful": 687,
            "failed": 102,
            "avg_delay_minutes": 28,
        },
    },
    "outer_west": {
        "id": "outer_west",
        "name": "Outer West (Heathrow corridor)",
        "example_postcodes": ["TW3", "TW6", "TW14", "UB1", "UB3", "UB8", "SL3"],
        "centroid": {"lat": 51.490, "lon": -0.500},
        "delivery_success_rate": 0.90,
        "avg_transit_hours": 2.2,
        "demand_pressure": 0.58,
        "active_routes": 16,
        "complaint_rate": 0.08,
        "last_30_days": {
            "total_deliveries": 843,
            "successful": 759,
            "failed": 84,
            "avg_delay_minutes": 20,
        },
    },
    "outer_north": {
        "id": "outer_north",
        "name": "Outer North (Hertfordshire borders)",
        "example_postcodes": ["EN1", "EN3", "EN5", "HA0", "HA3", "WD6", "WD23"],
        "centroid": {"lat": 51.660, "lon": -0.180},
        "delivery_success_rate": 0.88,
        "avg_transit_hours": 2.5,
        "demand_pressure": 0.47,
        "active_routes": 13,
        "complaint_rate": 0.10,
        "last_30_days": {
            "total_deliveries": 534,
            "successful": 470,
            "failed": 64,
            "avg_delay_minutes": 25,
        },
    },
}


# ── Pending order queue ────────────────────────────────────────────────────────

PENDING_ORDERS: list[dict] = [
    {
        "order_id": "ORD-2026-0501",
        "customer": "Barts Health NHS Trust",
        "destination_lat": 51.5176,
        "destination_lon": -0.1011,
        "destination_label": "St Bartholomew's Hospital, EC1A 7BE",
        "order_value": 6800.00,
        "weight_kg": 42.0,
        "cargo_type": "fragile",
        "time_window_hours": 2.5,
        "priority": "critical",
        "created_at": "2026-05-05T07:30:00Z",
    },
    {
        "order_id": "ORD-2026-0502",
        "customer": "Shoreditch Tech Ltd",
        "destination_lat": 51.5225,
        "destination_lon": -0.0769,
        "destination_label": "Old Street, E1 6RF",
        "order_value": 2400.00,
        "weight_kg": 28.5,
        "cargo_type": "fragile",
        "time_window_hours": 4.0,
        "priority": "standard",
        "created_at": "2026-05-05T07:45:00Z",
    },
    {
        "order_id": "ORD-2026-0503",
        "customer": "Brixton Market Collective",
        "destination_lat": 51.4613,
        "destination_lon": -0.1148,
        "destination_label": "Brixton Market, SW9 8PR",
        "order_value": 890.00,
        "weight_kg": 115.0,
        "cargo_type": "refrigerated",
        "time_window_hours": 3.0,
        "priority": "urgent",
        "created_at": "2026-05-05T08:00:00Z",
    },
    {
        "order_id": "ORD-2026-0504",
        "customer": "Westfield Fashion Group",
        "destination_lat": 51.5074,
        "destination_lon": -0.2214,
        "destination_label": "Westfield London, W12 7GF",
        "order_value": 3200.00,
        "weight_kg": 65.0,
        "cargo_type": "general",
        "time_window_hours": 6.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:10:00Z",
    },
    {
        "order_id": "ORD-2026-0505",
        "customer": "Havering Pharmacy Group",
        "destination_lat": 51.5640,
        "destination_lon":  0.1960,
        "destination_label": "Romford, RM1 3ER",
        "order_value": 5100.00,
        "weight_kg": 18.0,
        "cargo_type": "fragile",
        "time_window_hours": 3.5,
        "priority": "urgent",
        "created_at": "2026-05-05T08:15:00Z",
    },
    {
        "order_id": "ORD-2026-0506",
        "customer": "Canary Wharf Associates",
        "destination_lat": 51.5054,
        "destination_lon": -0.0235,
        "destination_label": "Canada Square, E14 5AB",
        "order_value": 1750.00,
        "weight_kg": 95.0,
        "cargo_type": "general",
        "time_window_hours": 5.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:20:00Z",
    },
    {
        "order_id": "ORD-2026-0507",
        "customer": "Croydon Automotive",
        "destination_lat": 51.3754,
        "destination_lon": -0.1008,
        "destination_label": "Purley Way, CR0 4RG",
        "order_value": 4300.00,
        "weight_kg": 320.0,
        "cargo_type": "general",
        "time_window_hours": 8.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:25:00Z",
    },
    {
        "order_id": "ORD-2026-0508",
        "customer": "Chelsea Fine Arts",
        "destination_lat": 51.4876,
        "destination_lon": -0.1681,
        "destination_label": "King's Road, SW3 4PH",
        "order_value": 14500.00,
        "weight_kg": 12.0,
        "cargo_type": "fragile",
        "time_window_hours": 2.0,
        "priority": "critical",
        "created_at": "2026-05-05T08:30:00Z",
    },
    {
        "order_id": "ORD-2026-0509",
        "customer": "Enfield Fresh Foods",
        "destination_lat": 51.6522,
        "destination_lon": -0.0808,
        "destination_label": "Enfield Town, EN1 1TW",
        "order_value": 1100.00,
        "weight_kg": 88.0,
        "cargo_type": "refrigerated",
        "time_window_hours": 4.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:35:00Z",
    },
    {
        "order_id": "ORD-2026-0510",
        "customer": "Dartford Builders Merchant",
        "destination_lat": 51.4464,
        "destination_lon":  0.2180,
        "destination_label": "Dartford, DA1 2EF",
        "order_value": 2600.00,
        "weight_kg": 480.0,
        "cargo_type": "general",
        "time_window_hours": 10.0,
        "priority": "standard",
        "created_at": "2026-05-05T08:40:00Z",
    },
]
