export const SCENARIOS = [
  {
    id: 'convergence',
    label: 'Scenario 1',
    title: 'Clean Convergence',
    description: 'Standard routing with a clear winner. Both agents reach the same conclusion.',
    badgeLabel: 'CONVERGENCE',
    badgeColor: '#34d399',
    order: {
      order_id: 'ORD-2024-001',
      destination_lat: 51.5074,
      destination_lon: -0.1278,
      order_value: 1250.00,
      weight_kg: 8.5,
      time_window_hours: 6,
      cargo_type: 'fragile',
      priority: 'urgent',
      scenario: 'convergence',
    },
  },
  {
    id: 'qualification',
    label: 'Scenario 2',
    title: 'Qualification',
    description: 'Optimizer picks correctly, but Reasoner surfaces a zone risk the reward function cannot see.',
    badgeLabel: 'QUALIFICATION',
    badgeColor: '#fbbf24',
    order: {
      order_id: 'ORD-2024-002',
      destination_lat: 51.4861,
      destination_lon: -0.1420,
      order_value: 3400.00,
      weight_kg: 22.0,
      time_window_hours: 12,
      cargo_type: 'general',
      priority: 'standard',
      scenario: 'qualification',
    },
  },
  {
    id: 'override',
    label: 'Scenario 3',
    title: 'Override',
    description: 'Fairness constraint activated. Reasoner detects geographic service deprivation and overrides.',
    badgeLabel: 'OVERRIDE',
    badgeColor: '#f87171',
    order: {
      order_id: 'ORD-2024-003',
      destination_lat: 51.4571,
      destination_lon: -0.1157,
      order_value: 890.00,
      weight_kg: 45.0,
      time_window_hours: 24,
      cargo_type: 'general',
      priority: 'standard',
      scenario: 'override',
    },
  },
];
